server:
  port: 8762
spring:
  application:
    name: lagou-eureka-server # 应⽤名称，会在Eureka中作为服务的id标识
eureka:
  instance:
    hostname: mytesta
  client:
    service-url:
      defaultZone: http://mytestb:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

