server:
  port: 9006

eureka:
  client:
    service-url:
      defalutZone: http://mytesta:8761/eureka/,http://mytestb:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:@project.version@

spring:
  application:
    name: lagou-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Li-Ping/config-repo.git
          username: ****
          password: ****
          search-paths:
            - config-repo
      label: master

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  # springboot中暴露健康检查等断点接⼝
management:
  endpoints:
    web:
     exposure:
      include: "*"
    # 暴露健康接⼝的细节
  endpoint:
    health:
     show-details: always


