server:
  port: 9002
spring:
  application:
    name: lagou-cloud-gateway

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    gateway:
      routes:
        - id: lagou-service-code
          uri: lb://lagou-service-code
          predicates:
            - Path=/api/code/**
          filters:
            - StripPrefix=1
        - id: lagou-service-email
          uri: lb://lagou-service-email
          predicates:
            - Path=/api/email/**
          filters:
            - StripPrefix=1
        - id: lagou-service-user
          uri: lb://lagou-service-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defalutZone: http://mytesta:8761/eureka/,http://mytestb:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:@project.version@

management:
  endpoints:
    web:
      exposure:
        include: "*"

config:
  time: ${config.time}
  count: ${config.count}
