server:
  port: 8082
spring:
  application:
    name: lagou-service-email

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  ## QQ邮箱配置
  mail:
    host: ${mail.host} #发送邮件服务器 smtp.qq.com
    username: ${mail.username} #发送邮件的邮箱地址
    password: ${mail.password} #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: ${mail.properties.mail.smtp.port} #端口号465或587
    properties.mail.smtp.auth: ${mail.properties.mail.smtp.auth}
    properties.mail.smtp.starttls.enable: ${mail.properties.mail.smtp.starttls.enable}
    properties.mail.smtp.starttls.required: ${mail.properties.mail.smtp.starttls.required}
    properties.mail.smtp.ssl.enable: ${mail.properties.mail.smtp.ssl.enable}
    default-encoding: utf-8
    protocol: ${mail.protocol}

eureka:
  client:
    service-url:
      defalutZone: http://mytesta:8761/eureka/,http://mytestb:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:1.0-SNAPSHOT


management:
  endpoints:
    web:
      exposure:
        include: "*"